
CREATE DATABASE [Test1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Test1', FILENAME = N'/var/opt/mssql/data/Test1.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Test1_log', FILENAME = N'/var/opt/mssql/data/Test1_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [Test1] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [Test1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Test1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Test1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Test1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Test1] SET ARITHABORT OFF 
GO
ALTER DATABASE [Test1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Test1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Test1] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Test1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Test1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Test1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Test1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Test1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Test1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Test1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Test1] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Test1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Test1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Test1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Test1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Test1] SET  READ_WRITE 
GO
ALTER DATABASE [Test1] SET RECOVERY FULL 
GO
ALTER DATABASE [Test1] SET  MULTI_USER 
GO
ALTER DATABASE [Test1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Test1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Test1] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Test1]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Test1] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

USE [master]
GO
BACKUP DATABASE [Test1] TO  DISK = N'/var/opt/mssql/data/Test1.bak' WITH NOFORMAT, NOINIT,  NAME = N'Test1-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
BACKUP LOG [Test1] TO  DISK = N'/var/opt/mssql/data/Test1.bak' WITH NOFORMAT, NOINIT,  NAME = N'Test1-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

ALTER AVAILABILITY GROUP MyAG ADD DATABASE Test1;
WAITFOR DELAY '00:00:03';

SELECT * FROM sys.dm_hadr_automatic_seeding;
SELECT * FROM sys.dm_hadr_physical_seeding_stats;
