services:
  sqlnode1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlnode1
    hostname: sqlnode1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword1
      - MSSQL_PID=Developer
      - MSSQL_ENABLE_HADR=1
    ports:
      - "64001:1433"   # sqlnode1 direct
      - "63001:63001"  # AG Listener (172.20.0.20)
    user: root          # required so NET_ADMIN caps work for ip/iptables
    cap_add:
      - NET_ADMIN
    volumes:
      - sql1_data:/var/opt/mssql
      - ./certs:/certs
      - ./init-primary.sh:/usr/src/app/init-primary.sh
      - ./create-ag.sql:/usr/src/app/create-ag.sql
#     command: /bin/bash /usr/src/app/init-primary.sh
    command: /bin/bash -c "/usr/src/app/init-primary.sh & /opt/mssql/bin/sqlservr"
    networks:
      sql_ag_net:
        ipv4_address: 172.20.0.10


  sqlnode2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlnode2
    hostname: sqlnode2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword1
      - MSSQL_PID=Developer
      - MSSQL_ENABLE_HADR=1
    ports:
      - "64002:1433"   # sqlnode2 direct
    volumes:
      - sql2_data:/var/opt/mssql
      - ./certs:/certs
      - ./init-secondary.sh:/usr/src/app/init-secondary.sh
#      - ./join-ag.sql:/usr/src/app/join-ag.sql
    command: /bin/bash -c "/usr/src/app/init-secondary.sh & /opt/mssql/bin/sqlservr"
    networks:
      sql_ag_net:
        ipv4_address: 172.20.0.11


networks:
  sql_ag_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  sql1_data:
  sql2_data: